export const discordConfig = () => ({
  token: process.env.DISCORD_TOKEN,
  guildId: process.env.GUILD_ID,
  clientId: process.env.CLIENT_ID,
  DISCORD_C7AUTO_CHANNEL_ID: process.env.DISCORD_C7AUTO_CHANNEL_ID,
  DISCORD_ACTIVATION_CHANNEL_ID: process.env.DISCORD_ACTIVATION_CHANNEL_ID,
  SUPORTE_ROLE_ID: process.env.SUPORTE_ROLE_ID,
  CS_ROLE_ID: process.env.CS_ROLE_ID,
  TRAFEGO_ROLE_ID: process.env.TRAFEGO_ROLE_ID,
  FINANCEIRO_ROLE_ID: process.env.FINANCEIRO_ROLE_ID,
  SUPORTE_CHANNEL_ID: process.env.SUPORTE_CHANNEL_ID,
  CS_CHANNEL_ID: process.env.CS_CHANNEL_ID,
  TRAFEGO_CHANNEL_ID: process.env.TRAFEGO_CHANNEL_ID,
  FINANCEIRO_CHANNEL_ID: process.env.FINANCEIRO_CHANNEL_ID,
  intents: [
    'Guilds',
    'GuildMessages',
    'GuildMembers',
    'MessageContent',
    'DirectMessages',
  ],
});
